name: build thesis
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: set up git repository
        uses: actions/checkout@v3
      - name: compile latex document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: tex
          compiler: arara
          args: --verbose
          root_file: 0_tcc.tex
      - name: release thesis
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          target_commitish: ${{ github.sha }}
          name: Predictive Dispatch Strategies of Hybrid Energy System with Neural Networks
          files: tex/0_tcc.pdf
